# Generated by Django 4.2.13 on 2024-10-23 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectedLinks',
            fields=[
                ('name', models.TextField()),
                ('url', models.URLField(primary_key=True, serialize=False)),
                ('folder', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExportedResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField()),
                ('taxonomy_level', models.TextField(blank=True, null=True)),
                ('downloaded_file', models.TextField(blank=True, null=True)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.collectedlinks')),
            ],
            options={
                'unique_together': {('url', 'result', 'taxonomy_level')},
            },
        ),
    ]
