# Generated by Django 4.2.13 on 2024-10-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_collectedlinks_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectedlinks',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collectedlinks',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
