# Generated by Django 4.2.13 on 2024-10-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_rename_url_exportedresults_collected_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectedlinks',
            name='job_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collectedlinks',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='exportedresults',
            name='job_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exportedresults',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
