# Generated by Django 4.2.13 on 2024-10-26 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_collectedlinks_job_id_collectedlinks_last_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingJob',
            fields=[
                ('job_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('status', models.CharField(default='In Progress', max_length=50)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'scraping_job',
            },
        ),
        migrations.AlterField(
            model_name='collectedlinks',
            name='job_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collected_links', to='apis.scrapingjob'),
        ),
        migrations.AlterField(
            model_name='exportedresults',
            name='job_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exported_results', to='apis.scrapingjob'),
        ),
    ]
