# Generated by Django 4.2.13 on 2024-10-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_scrapingjob_alter_collectedlinks_job_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportedresults',
            name='url',
            field=models.URLField(default='N/A', unique=True),
            preserve_default=False,
        ),
    ]
